### ISSUE TITLE
Bug in map creation

### ISSUE THREAD

**Issue by Hew0914** [openflam/spatial-server#7]
In polycam.py, the function build_map_from_polycam_output calls _prepare_images_file on line 268. This function is passed 2 dictionaries, imgname_to_imgid and imgname_to_cameraid. While the cameraid one seems to be fine, the imgid dictionary is not filled, causing _prepare_images_file to brick on line 87 when it tries to access an entry. It seems that querying the sqlite table gives an empty set, implying either the data is not entered into the table properly or the cur.execute statement on line 259 is improperly formatted. I have messed with the execute, and it seems the table is created properly with the images column existing, but seemingly nothing is in the column

**Comment by SagarB-97** [comment]
Corrected in the latest version
